//public class Exception_2 {
//    public static void main(String[] args) {
//        try {
//            int sum=5/0;
//            throw  new ArithmeticException("demo");
//            int[] a=new int[5];
//            a[10]=7;
//            throw new ArrayIndexOutOfBoundsException("Exception");
////            int a=5,b=7;
//            System.out.println("Addition="+(a+b)catch);
//
//
//        }
//        catch (ArrayIndexOutOfBoundsException e){
//            System.out.println(e);
//        }ArithmeticException
//        catch (ArithmeticException e){
//            System.out.println(e);
//        }
//        catch (Exception e){
//            System.out.println(e);
//        }class
//
//    }
//
//
//}
